# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "file", source: "trivago", destination: "/home/vagrant/trivago"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update --yes
    sudo apt-get install -y python-pip
    cd /home/vagrant/trivago
    sudo pip install -r requirements.txt
    sudo python setup.py install
  SHELL
end
